web:
  image: webdevops/php-apache
  environment:
    - WEB_DOCUMENT_ROOT=/src
    - ALLOW_OVERRIDE=true
  ports:
    - "80:80"
  links:
    - data
  volumes:
    - ./src:/src

data:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"
